---
image_resource:
  type: registry-image
  source:
    repository: brenix/alpine-bash-git-ssh
    tag: latest
    username: ((license-finder-docker-username))
    password: ((license-finder-docker-password))
platform: linux
inputs:
- name: lf-git
- name: lf-release
- name: semver-version
outputs:
- name: lf-git-changed
- name: version
run:
  path: lf-git/ci/scripts/updateChangelog.sh
